version: "3"

services:
  # mysql
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    restart: always
    # tty: true
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: sample_db

  # uWSGI + Flask
  python:
    build: ./python
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - "./python/src:/src"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    command: flask run -h 0.0.0.0

  # Nginx
  proxy:
    depends_on:
      - python
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/log:/var/log/nginx
